#!/bin/bash

# 百度云BOS对象存储配置
export BAIDU_BCE_ACCESS_KEY_ID=05c5a1cf304f45c6b17f55967449bc9b
export BAIDU_BCE_SECRET_ACCESS_KEY=42d4dea8b0614fc09488c9386bad9909
export BAIDU_BOS_ENDPOINT=bj.bcebos.com
export BAIDU_BOS_BUCKET=ezijing
export BAIDU_BOS_DOMAIN=https://ezijing.bj.bcebos.com

echo "百度云BOS配置环境变量已设置"
echo "BAIDU_BCE_ACCESS_KEY_ID: $BAIDU_BCE_ACCESS_KEY_ID"
echo "BAIDU_BCE_SECRET_ACCESS_KEY: ${BAIDU_BCE_SECRET_ACCESS_KEY:0:5}..."
echo "BAIDU_BOS_ENDPOINT: $BAIDU_BOS_ENDPOINT"
echo "BAIDU_BOS_BUCKET: $BAIDU_BOS_BUCKET"
echo "BAIDU_BOS_DOMAIN: $BAIDU_BOS_DOMAIN" 